# Admin-only mutation to create a user with a specific ID

mutation AdminCreateUser($id: String!, $displayName: String!, $photoURL: String!) @auth(level: NO_ACCESS) {
  user_insert(data: { id: $id, displayName: $displayName, photoURL: $photoURL })
}

query AdminGetUser($id: String!) @auth(level: NO_ACCESS) {
  user(id: $id) {
    id
    displayName
    photoURL
  }
}
